spring:
  application:
    name: case-server

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
      output-bindings: publishCaseImport-out-0

powsybl-ws:
  database:
    name: case_metadata

cleaning-cases-cron: 0 0 2 * * ?

storage:
  type: FS  # FS or S3

case-subpath: cases
