spring:
  application:
    name: case-server

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
      output-bindings: publishCaseImport-out-0
    aws:
      s3:
        path-style-access-enabled: true
      endpoint: http://172.17.0.1:19000
      region:
        profile:
          name: default
        static: test
      bucket: bucket-gridsuite
      credentials:
        access-key: minioadmin
        secret-key: minioadmin

powsybl-ws:
  database:
    name: case_metadata

cleaning-cases-cron: 0 * 2 * * ?

storage:
  type: S3  # file or S3