spring:
  application:
    name: case-server

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
      output-bindings: publishCaseImport-out-0
    aws:
      s3:
        path-style-access-enabled: true
      # classic minio port, useful default for exploring
      endpoint: http://s3-storage:9000
      region:
        profile:
          name: default
        static: test
      bucket: my-bucket
      credentials:
        access-key: minioadmin
        secret-key: minioadmin

powsybl-ws:
  database:
    name: case_metadata

cleaning-cases-cron: 0 0 2 * * ?

storage:
  type: FS  # FS or S3

case-subpath: cases

server:
  compression:
    enabled: true
    min-response-size: 1MB
    mime-types: application/octet-stream
