spring:
  application:
    name: case-server

  cloud:
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
      output-bindings: publishCaseImport-out-0

powsybl-ws:
  database:
    name: case_metadata

cleaning-cases-cron: 0 * 2 * * ?

cloud:
  aws:
    credentials:
      access-key: minioadmin
      secret-key: minioadmin
    s3:
      endpoint: http://minio:9000

case-store-bucket: bucket-gridsuite
