server:
  port: 5000

spring:
  rabbitmq:
    addresses: localhost

  elasticsearch:
    uris:
      - http://localhost:9200
    connection-timeout: 60s
    socket-timeout: 60s
    ## to fill if authentication is needed
    # username:
    # password:
  cloud:
    aws:
      endpoint: http://localhost:19000

powsybl-ws:
  database:
    host: localhost

cleaning-cases-cron: 0 * 2 * * ?