name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-generic.yml@baf0d2ed84b70d359132693880d5e530cd93f168
    with:
      sonarOrganization: powsybl-ci-github
      sonarProjectKey: com.powsybl:powsybl-case-server
      dockerImage: docker.io/powsybl/case-server
      dockerUsername: powsyblci
      eventType: case_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
