name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@5e13dcb03778dc9a47bd0adbd84c48392b32cd46
    with:
      sonarOrganization: powsybl-ci-github
      sonarProjectKey: com.powsybl:powsybl-case-server
      dockerImage: docker.io/powsybl/case-server
      dockerUsername: powsyblci
      eventOrganizations: gridsuite
      eventType: case_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
