name: CI

on:
  push:
    branches:
      - 'main'
      - 'branch-test2'
    tags:
      - 'v[0-9]*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build case server with Maven
        run: mvn --batch-mode -Pjacoco install

      #We only run the sonar analysis on the server directory because we can't push 2 sonar result to the same sonar repository
      #TODO add the analysis on the client when the client and server are split into 2 differents github repo
      - name: Run SonarCloud analysis on case server
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-case-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@main
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          organizations: gridsuite
          event-type: case_server_updated
