name: CI

on:
  push:
    branches:
      - 'branch-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Checkout sources
        uses: actions/checkout@v1

      #   - name: Build with Maven
      #     run: mvn --batch-mode -Pjacoco install

      - name: Run SonarCloud analysis on server
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-case-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
